name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release title (e.g., v2.0 with aaudio_mmap)'
        required: true
      versionCode:
        description: 'Release version code (e.g., xx000)'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate versionCode format
        run: |
          if [[ ! "${{ github.event.inputs.versionCode }}" =~ ^[0-9]{5}$ ]]; then
            echo "Error: versionCode must be 5 digits (e.g., 21000)"
            exit 1
          fi

      - name: Compress files (improved exclusion)
        run: |
          # Create zip with proper exclusion
          find . -mindepth 1 \
            -not -path './.git*' \
            -not -path './.github*' \
            -not -path './README.md' \
            -not -path './LICENSE' \
            -not -path './update/*' \
            -not -path './files/*' \
            -exec zip -9r ./HiResAudio-aaudio_mmap.zip {} +

      - name: Create release for tag release
        run: |
          # Extract major (2), minor (1), and build (000) from versionCode 21000
          MAJOR=$(echo "${{ github.event.inputs.versionCode }}" | cut -c1)
          MINOR=$(echo "${{ github.event.inputs.versionCode }}" | cut -c2)
          BUILD=$(echo "${{ github.event.inputs.versionCode }}" | cut -c3-5)
          
          TAG="${MAJOR}.${MINOR}-${BUILD}"
          echo "Creating release with tag: ${TAG}"
          
          gh release create "${TAG}" \
            --title "${{ github.event.inputs.version }}" \
            ./HiResAudio-aaudio_mmap.zip -F ./update/changelog.md
        env:
          GH_TOKEN: ${{ github.token }}
