name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., x.x with?)'
        required: true
      versionCode:
        description: 'Release version code (e.g., xxxx)'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Writing the variables
        run: cat ./module.prop | tee -a "${GITHUB_ENV}"

      - name: Compressing
        run: |
          zip -9rv ./HiResAudio-aaudio_mmap.zip ./* -x ./.git ./.github ./README.md \
            ./update/update.json ./update/changelog.md

      - name: Create release
        run: |
          gh release create "${{ github.event.inputs.version }}" \
            ./HiResAudio-aaudio_mmap.zip -F ./update/changelog.md
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Update service files
        run: |
          python3 ./.github/mkjson "${{ github.event.inputs.version }}" "${{ github.event.inputs.versionCode }}" \
            "https://github.com/adivenxnataly/Hi-ResAudio/releases/download/${{ github.event.inputs.version }}/HiResAudio-aaudio_mmap.zip" \
            "https://github.com/adivenxnataly/Hi-ResAudio/releases/latest"
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add ./update/update.json
          git commit -m 'JSON update'
          git push
