name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release title (e.g., v2.0 with aaudio_mmap)'
        required: true
      versionCode:
        description: 'Release version code (e.g., 20000)'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Writing the variables
        run: cat ./module.prop | tee -a "${GITHUB_ENV}"

      - name: Compressing
        run: |
          zip -9rv ./HiResAudio-aaudio_mmap.zip ./* -x ./.git ./.github ./README.md ./LICENSE ./update ./files

      - name: Create release
        run: |
          # Format versionCode to create tag (e.g., 20000 -> 2.0-000)
          TAG=$(echo "${{ github.event.inputs.versionCode }}" | sed 's/\(..\)\(...\)/\1-\2/')
          
          # Create release with tag and title
          gh release create "${TAG}" \
            --title "${{ github.event.inputs.version }}" \
            ./HiResAudio-aaudio_mmap.zip -F ./update/changelog.md
        env:
          GH_TOKEN: ${{ github.token }}
